
import { Category, Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'ytm_01',
    name: 'Liv-Guard Syrup',
    hindiName: 'लिव-गार्ड सिरप',
    category: Category.MEDICINE,
    benefits: 'Liver detox, improves appetite, jaundice recovery, and overall liver health.',
    hindiBenefits: 'लिवर डिटॉक्स, भूख में सुधार, पीलिया से रिकवरी और लिवर का स्वास्थ्य।',
    dosage: '10ml twice a day before meals.',
    hindiDosage: '10 मिली दिन में दो बार खाना खाने से पहले।',
    description: 'An Ayurvedic formulation for protecting the liver from toxins and improving metabolic health.',
    ingredients: ['Bhringraj', 'Kutki', 'Punarnava'],
    searchKeywords: ['liver', 'jigar', 'bhukh', 'jaundice', 'piliya', 'liver detox', 'bhuk']
  },
  {
    id: 'ytm_02',
    name: 'Eye Amrut',
    hindiName: 'आई अमृत',
    category: Category.MEDICINE,
    benefits: 'Reduces dependency on glasses, treats glaucoma, redness, itching, and watery eyes.',
    hindiBenefits: 'चश्मे की निर्भरता कम करता है, ग्लूकोमा, लाली और खुजली का इलाज करता है।',
    dosage: 'Oil: Apply like kajal. Powder: Soak in water overnight, strain, put 3–4 drops.',
    hindiDosage: 'तेल: काजल की तरह लगाएं। पाउडर: रात भर पानी में भिगोएं, छानकर 3-4 बूंद डालें।',
    description: 'A complete natural eye care solution for vision clarity.',
    ingredients: ['Natural Herbal Extracts', 'Eye-cooling minerals'],
    searchKeywords: ['aankh', 'eye', 'vision', 'chashma', 'glaucoma', 'itni', 'khujli', 'vision clarity']
  },
  {
    id: 'ytm_03',
    name: 'Hridhu Rakshak Ras',
    hindiName: 'हृदु रक्षक रस',
    category: Category.MEDICINE,
    benefits: 'Improves blood circulation, strengthens heart muscles, manages cholesterol and BP.',
    hindiBenefits: 'रक्त संचार में सुधार, हृदय की मांसपेशियों की मजबूती, कोलेस्ट्रॉल और बीपी नियंत्रण।',
    dosage: '15 ml mixed with lukewarm water on an empty stomach daily.',
    hindiDosage: 'रोजाना खाली पेट 15 मिली गुनगुने पानी के साथ।',
    description: 'Potent heart-health juice for cardiovascular support.',
    ingredients: ['Arjunchal', 'Garlic', 'Moringa', 'Ginger', 'Lemon', 'Honey'],
    searchKeywords: ['heart', 'dil', 'cholesterol', 'blood pressure', 'bp', 'circulation', 'nas']
  },
  {
    id: 'ytm_04',
    name: 'Sea Buckthorn',
    hindiName: 'सी बकथॉर्न',
    category: Category.SUPPLEMENT,
    benefits: 'Glowing skin, anti-aging, immunity booster, liver detox, and heart health.',
    hindiBenefits: 'चमकदार त्वचा, एंटी-एजिंग, इम्युनिटी बूस्टर और लिवर डिटॉक्स।',
    dosage: 'Adults: 20–30 ml twice a day. Children: 5–10 ml twice a day.',
    hindiDosage: 'वयस्क: 20-30 मिली दिन में दो बार। बच्चे: 5-10 मिली।',
    description: 'Nutrient-rich drink with vitamins A, C, E and Omega 3, 6, 7, 9.',
    ingredients: ['Sea Buckthorn Berry', 'Omega Fatty Acids'],
    searchKeywords: ['skin', 'immunity', 'anti-aging', 'detox', 'omega', 'vitamin c', 'chehra', 'glow']
  },
  {
    id: 'ytm_05',
    name: 'AYUSH KWATH Tablet',
    hindiName: 'आयुष क्वाथ टेबलेट',
    category: Category.SUPPLEMENT,
    benefits: 'Boosts immunity, natural remedy for viral fever, and relieves infections.',
    hindiBenefits: 'इम्युनिटी बढ़ाता है, वायरल बुखार का प्राकृतिक इलाज और संक्रमण से राहत।',
    dosage: 'Dissolve 2 tablets in 150 ml boiled water. Drink like tea.',
    hindiDosage: '150 मिली उबले पानी में 2 गोली घोलें। चाय की तरह पिएं।',
    description: 'Traditional herbal kadha in convenient tablet form.',
    ingredients: ['Tulsi', 'Dalchini', 'Sunthi', 'Krishna Mirch'],
    searchKeywords: ['kadha', 'immunity', 'fever', 'bukhaar', 'viral', 'infection', 'tea', 'chai']
  },
  {
    id: 'ytm_06',
    name: 'Cholesty',
    hindiName: 'कोलेस्टी',
    category: Category.MEDICINE,
    benefits: 'Lowers cholesterol and triglycerides, reduces heart disease risk.',
    hindiBenefits: 'कोलेस्ट्रॉल और ट्राइग्लिसराइड्स कम करता है, हृदय रोगों का खतरा घटाता।',
    dosage: 'Initial: 2 tabs 3x/day. Maintenance: 2 tabs 2x/day.',
    hindiDosage: 'शुरुआत: 2 गोली दिन में 3 बार। बाद में: 2 गोली दिन में 2 बार।',
    description: 'Herbal lipid management for heart health.',
    ingredients: ['Chitrak', 'Arjun', 'Amla'],
    searchKeywords: ['cholesterol', 'fat', 'triglycerides', 'heart', 'dil', 'motapa']
  },
  {
    id: 'ytm_07',
    name: 'Mahasudarshan Tablet',
    hindiName: 'महासुदर्शन टेबलेट',
    category: Category.MEDICINE,
    benefits: 'Manages fevers (dengue, malaria, typhoid), relieves body pain, and boosts immunity.',
    hindiBenefits: 'बुखार (डेंगू, मलेरिया, टाइफाइड), शरीर दर्द और इम्युनिटी में सहायक।',
    dosage: 'Adults: 1–2 tabs 3x/day. Children: 1 tab 3x/day.',
    hindiDosage: 'वयस्क: 1-2 गोली दिन में 3 बार। बच्चे: 1 गोली दिन में 3 बार।',
    description: 'Effective Ayurvedic anti-pyretic and infection fighter.',
    ingredients: ['Mahasudarshan Churna extract'],
    searchKeywords: ['fever', 'bukhaar', 'malaria', 'dengue', 'typhoid', 'immunity', 'body pain', 'sharir dard']
  },
  {
    id: 'ytm_08',
    name: 'Giloy Ghanvati',
    hindiName: 'गिलोय घनवटी',
    category: Category.SUPPLEMENT,
    benefits: 'Detoxifies liver, boosts immunity against asthma, reduces stress.',
    hindiBenefits: 'लिवर डिटॉक्स, अस्थमा के खिलाफ इम्युनिटी और तनाव में कमी।',
    dosage: '2 tablets, 3 times a day.',
    hindiDosage: '2 गोली, दिन में 3 बार।',
    description: 'Concentrated Giloy for overall metabolic health.',
    ingredients: ['Pure Giloy extract'],
    searchKeywords: ['giloy', 'immunity', 'asthma', 'stress', 'detox', 'liver', 'bukhar']
  },
  {
    id: 'ytm_09',
    name: 'DIA-AMBRO',
    hindiName: 'डाई-एम्ब्रो',
    category: Category.MEDICINE,
    benefits: 'Controls blood sugar naturally and reduces post-meal sugar spikes.',
    hindiBenefits: 'ब्लड शुगर को प्राकृतिक रूप से नियंत्रित करता है।',
    dosage: '1–2 tablets 3 times a day, 15 minutes before meals.',
    hindiDosage: '1-2 गोली दिन में 3 बार, खाने से 15 मिनट पहले।',
    description: 'Diabetes management with Gudmar and Karela.',
    ingredients: ['Gudmar', 'Jambu Beej', 'Karela'],
    searchKeywords: ['sugar', 'diabetes', 'madhumeh', 'blood sugar', 'insuln']
  },
  {
    id: 'ytm_10',
    name: 'Tulsi CC Syrup',
    hindiName: 'तुलसी सीसी सिरप',
    category: Category.MEDICINE,
    benefits: 'Relieves all types of cough, soothes sore throat, and supports asthma patients.',
    hindiBenefits: 'हर तरह की खांसी और गले की खराश से राहत।',
    dosage: 'Adults: 10ml 2–3 times a day. Children: 5ml.',
    hindiDosage: 'वयस्क: 10 मिली दिन में 2-3 बार। बच्चे: 5 मिली।',
    description: 'Herbal lung tonic and cough relief.',
    ingredients: ['Pushkar Mool', 'Yastimadh', 'Tulsi'],
    searchKeywords: ['cough', 'khansi', 'asthma', 'gala', 'throat', 'khashkhash', 'lung']
  },
  {
    id: 'ytm_11',
    name: 'NORMAL-AM Tablets',
    hindiName: 'नॉर्मल-एएम टेबलेट्स',
    category: Category.MEDICINE,
    benefits: 'Controls BP, reduces anxiety, and improves focus without sleepiness.',
    hindiBenefits: 'बीपी नियंत्रण, चिंता कम करना और एकाग्रता में सुधार।',
    dosage: 'Initial: 2 tabs 3x/day. Maintenance: 2 tabs 2x/day.',
    hindiDosage: 'शुरुआत: 2 गोली दिन में 3 बार। बाद में: 2 गोली दिन में 2 बार।',
    description: 'Natural hypertension and stress management.',
    ingredients: ['Sarpagandha', 'Ashwagandha'],
    searchKeywords: ['bp', 'blood pressure', 'anxiety', 'stress', 'tension', 'focus', 'manish']
  },
  {
    id: 'ytm_12',
    name: 'Multi Fitup',
    hindiName: 'मल्टी फिटअप',
    category: Category.SUPPLEMENT,
    benefits: 'Reduces weakness, improves digestion, and increases appetite.',
    hindiBenefits: 'कमजोरी कम करता है, पाचन में सुधार और भूख बढ़ाता है।',
    dosage: 'Adults: 2 tsp 2–3 times a day.',
    hindiDosage: 'वयस्क: 2 चम्मच दिन में 2-3 बार।',
    description: 'Complete health tonic for energy.',
    ingredients: ['Ashwagandha', 'Munnaka'],
    searchKeywords: ['weakness', 'kamzori', 'appetite', 'bhukh', 'digestion', 'pachan', 'energy']
  },
  {
    id: 'ytm_13',
    name: 'Alkafyn',
    hindiName: 'अल्काफिन',
    category: Category.MEDICINE,
    benefits: 'Relieves burning during urination and keeps bladder healthy.',
    hindiBenefits: 'पेशाब के दौरान जलन से राहत और मूत्राशय का स्वास्थ्य।',
    dosage: 'Adults: 2 tsp 2–3 times/day.',
    hindiDosage: 'वयस्क: 2 चम्मच दिन में 2-3 बार।',
    description: 'Urinary system cleanser and alkalizer.',
    ingredients: ['Gokhru', 'Punarnava', 'Giloy'],
    searchKeywords: ['urine', 'peshab', 'burning', 'jalan', 'bladder', 'kidney', 'uti']
  },
  {
    id: 'ytm_14',
    name: 'Vaat Bhasma Vati',
    hindiName: 'वात भस्म वटी',
    category: Category.MEDICINE,
    benefits: 'Relieves arthritis, joint pain, and strengthens nerves.',
    hindiBenefits: 'गठिया, जोड़ों के दर्द से राहत और नसों की मजबूती।',
    dosage: '1-2 pills 2x/day. Chew or crush before swallowing.',
    hindiDosage: '1-2 गोली दिन में 2 बार। निगलने से पहले चबाएं या कुचलें।',
    description: 'Traditional orthopedic care pill.',
    ingredients: ['Purified minerals', 'Anti-inflammatory herbs'],
    searchKeywords: ['joint pain', 'ghutne dard', 'arthritis', 'gathiya', 'nerve', 'nas', 'dard']
  },
  {
    id: 'ytm_15',
    name: 'Vaat Bhasm Syrup',
    hindiName: 'वात भस्म सिरप',
    category: Category.MEDICINE,
    benefits: 'Balances Vata dosha, reduces swelling, improves flexibility.',
    hindiBenefits: 'वात दोष संतुलन, सूजन में कमी और लचीलेपन में सुधार।',
    dosage: '10ml twice a day.',
    hindiDosage: '10 मिली दिन में दो बार।',
    description: 'Liquid relief for sciatica and cervical pain.',
    ingredients: ['Vata-balancing herbs'],
    searchKeywords: ['sciatica', 'cervical', 'back pain', 'kamar dard', 'swelling', 'sujan', 'vaat']
  },
  {
    id: 'ytm_16',
    name: 'Stono Amrit Capsule',
    hindiName: 'स्टोनो अमृत कैप्सूल',
    category: Category.MEDICINE,
    benefits: 'Removes kidney stones by breaking them into smaller pieces.',
    hindiBenefits: 'किडनी की पथरी को तोड़कर बाहर निकालने में सहायक।',
    dosage: 'First 2 Weeks: 2 caps 3x/day. Then: 2 caps 2x/day.',
    hindiDosage: 'पहले 2 हफ्ते: 2 कैप्सूल दिन में 3 बार। बाद में: 2 कैप्सूल दिन में 2 बार।',
    description: 'Specialized formula for kidney stone flushing.',
    ingredients: ['Pashanbhed', 'Varun'],
    searchKeywords: ['stone', 'pathri', 'kidney stone', 'gurda pathri', 'urine']
  },
  {
    id: 'ytm_17',
    name: 'Rakht Shodhak',
    hindiName: 'रक्त शोधक',
    category: Category.SUPPLEMENT,
    benefits: 'Purifies blood, manages anemia, improves digestion, and boosts immunity.',
    hindiBenefits: 'खून साफ करता है, एनीमिया नियंत्रण और इम्युनिटी बढ़ाता है।',
    dosage: 'Adults: 10 ml twice daily.',
    hindiDosage: 'वयस्क: 10 मिली दिन में दो बार।',
    description: 'Natural herbal syrup for blood health.',
    ingredients: ['Papaya', 'Giloy', 'Amla'],
    searchKeywords: ['blood purifier', 'khoon saaf', 'anemia', 'haemoglobin', 'pimple', 'skin']
  },
  {
    id: 'ytm_18',
    name: 'PILENT',
    hindiName: 'पायलेंट',
    category: Category.MEDICINE,
    benefits: 'Reduces pain, swelling, and bleeding in piles. Softens stools.',
    hindiBenefits: 'बवासीर में दर्द, सूजन और रक्तस्राव को कम करता है।',
    dosage: 'Tabs: 2 tabs 3x/day. Syrup: 2 tsp 3x/day.',
    hindiDosage: 'गोली: 2 गोली दिन में 3 बार। सिरप: 2 चम्मच दिन में 3 बार।',
    description: 'Available in tablets and syrup for hemorrhoids relief.',
    ingredients: ['Laxative herbs'],
    searchKeywords: ['piles', 'bawasir', 'constipation', 'kabj', 'bleeding', 'stool']
  },
  {
    id: 'ytm_19',
    name: 'Twin Apple Tablets',
    hindiName: 'ट्विन एप्पल टेबलेट्स',
    category: Category.SUPPLEMENT,
    benefits: 'Youthful skin, anti-aging, firming, and hydration.',
    hindiBenefits: 'जवान त्वचा, एंटी-एजिंग, कसाव और हाइड्रेशन।',
    dosage: 'Place under the tongue morning and night. Let dissolve slowly.',
    hindiDosage: 'सुबह और रात को जीभ के नीचे रखें। धीरे-धीरे घुलने दें।',
    description: 'Advanced skin-health tablets with stem cell technology.',
    ingredients: ['Apple Stem Cells', 'Grape Stem Cells'],
    searchKeywords: ['skin', 'chehra', 'anti-aging', 'glow', 'wrinkles', 'stem cell']
  },
  {
    id: 'ytm_20',
    name: 'Thenga Powder',
    hindiName: 'थेंगा पाउडर',
    category: Category.MEDICINE,
    benefits: 'Removes kidney stones and keeps kidneys healthy.',
    hindiBenefits: 'किडनी की पथरी हटाता है और किडनी को स्वस्थ रखता है।',
    dosage: 'Take as directed for flushing out stones.',
    hindiDosage: 'निर्देशानुसार पथरी निकालने के लिए लें।',
    description: 'Natural powder for stone removal and urine flow.',
    ingredients: ['Kidney-health herbs'],
    searchKeywords: ['stone', 'pathri', 'kidney', 'urine', 'flush']
  },
  {
    id: 'ytm_21',
    name: 'Thiaro-Am',
    hindiName: 'थियारो-एएम',
    category: Category.MEDICINE,
    benefits: 'Supports thyroid health, reduces fatigue, improves metabolism.',
    hindiBenefits: 'थायराइड स्वास्थ्य, थकान में कमी और मेटाबॉलिज्म में सुधार।',
    dosage: 'Initial: 2 tabs 3x/day. Maintenance: 2 tabs 2x/day.',
    hindiDosage: 'शुरुआत: 2 गोली दिन में 3 बार। बाद में: 2 गोली दिन में 2 बार।',
    description: 'Herbal thyroid and brain function support.',
    ingredients: ['Ashwagandha', 'Kanchanar'],
    searchKeywords: ['thyroid', 'metabolism', 'fatigue', 'thakan', 'hormone']
  },
  {
    id: 'ytm_22',
    name: 'Vatsa-Ton',
    hindiName: 'वत्स-टोन',
    category: Category.SUPPLEMENT,
    benefits: 'Increases stamina, sexual health, and reduces tiredness.',
    hindiBenefits: 'स्टैमिना बढ़ाता है, यौन स्वास्थ्य और थकान में कमी।',
    dosage: 'First 2 weeks: 2 tabs 3x/day. After: 2 tabs 2x/day.',
    hindiDosage: 'पहले 2 हफ्ते: 2 गोली दिन में 3 बार। बाद में: 2 गोली दिन में 2 बार।',
    description: 'Energy and vigor booster for men.',
    ingredients: ['Strength-boosting herbs'],
    searchKeywords: ['stamina', 'men health', 'energy', 'vigor', 'vitality', 'sex health', 'mardana kamzori']
  },
  {
    id: 'ytm_23',
    name: 'URICID Capsules',
    hindiName: 'यूरिसिड कैप्सूल्स',
    category: Category.MEDICINE,
    benefits: 'Controls uric acid, cleans blood, reduces joint pain.',
    hindiBenefits: 'यूरिक एसिड नियंत्रण, खून की सफाई और जोड़ों के दर्द में राहत।',
    dosage: '1 capsule daily.',
    hindiDosage: '1 कैप्सूल रोजाना।',
    description: 'Herbal uric acid management.',
    ingredients: ['Blood-cleansing herbs'],
    searchKeywords: ['uric acid', 'joint pain', 'ghutne dard', 'blood clean', 'gout']
  },
  {
    id: 'ytm_24',
    name: 'Lady Fit Syrup',
    hindiName: 'लेडी फिट सिरप',
    category: Category.MEDICINE,
    benefits: 'Helps with white discharge (leucorrhoea) and irregular periods.',
    hindiBenefits: 'सफेद पानी (ल्यूकोरिया) और अनियमित मासिक धर्म में सहायक।',
    dosage: '2 tsp 20 minutes AFTER Lucco tablets.',
    hindiDosage: 'लुक्को टेबलेट्स के 20 मिनट बाद 2 चम्मच।',
    description: 'Uterine health tonic for women.',
    ingredients: ['Female health herbs'],
    searchKeywords: ['ladies health', 'period', 'white discharge', 'leucorrhoea', 'mahina', 'uterine']
  },
  {
    id: 'ytm_25',
    name: 'KAMBAKKHT KABJ Churna',
    hindiName: 'कम्बख्त कब्ज चूर्ण',
    category: Category.MEDICINE,
    benefits: 'Relieves chronic constipation and acidity.',
    hindiBenefits: 'पुरानी कब्ज और एसिडिटी से राहत।',
    dosage: '1/2 to 1 tsp at bedtime with water.',
    hindiDosage: 'आधा से एक चम्मच सोते समय पानी के साथ।',
    description: 'Natural powder for safe digestion relief.',
    ingredients: ['Sonamukhi', 'Harde', 'Sunth'],
    searchKeywords: ['constipation', 'kabj', 'acidity', 'gas', 'pachan', 'pet dard']
  },
  {
    id: 'ytm_26',
    name: 'Lucco Tablets',
    hindiName: 'लुक्को टेबलेट्स',
    category: Category.MEDICINE,
    benefits: 'Treats leucorrhoea and regulates menstrual cycles.',
    hindiBenefits: 'ल्यूकोरिया का इलाज और मासिक धर्म चक्र का नियमन।',
    dosage: '2 tablets morning and evening, 30 mins after meals.',
    hindiDosage: 'सुबह और शाम 2 गोली, खाने के 30 मिनट बाद।',
    description: 'Internal medicine for female reproductive health.',
    ingredients: ['Uterine health extracts'],
    searchKeywords: ['leucorrhoea', 'white discharge', 'periods', 'ladies', 'uterine']
  },
  {
    id: 'ytm_27',
    name: 'Neuro Shakti Spray',
    hindiName: 'न्यूरो शक्ति स्प्रे',
    category: Category.MEDICINE,
    benefits: 'Reduces stress, improves memory, supports mental health.',
    hindiBenefits: 'तनाव कम करता है, याददाश्त में सुधार और मानसिक स्वास्थ्य।',
    dosage: '6-7 sprays in mouth at sleep time.',
    hindiDosage: 'सोते समय मुंह में 6-7 स्प्रे।',
    description: 'Herbal mouth spray for brain focus.',
    ingredients: ['Brahmi', 'Ginger'],
    searchKeywords: ['brain', 'memory', 'stress', 'dimag', 'tension', 'sleep', 'neend']
  },
  {
    id: 'ytm_28',
    name: 'Neuro Shakti Syrup',
    hindiName: 'न्यूरो शक्ति सिरप',
    category: Category.MEDICINE,
    benefits: 'Reduces mental tension and weakness.',
    hindiBenefits: 'मानसिक तनाव और कमजोरी को कम करता है।',
    dosage: '15 ml twice daily. Take 20 mins after Neuro Shakti Malt.',
    hindiDosage: '15 मिली दिन में दो बार। न्यूरो शक्ति माल्ट के 20 मिनट बाद लें।',
    description: 'Brain and nerve tonic.',
    ingredients: ['Brahmi', 'Ginger'],
    searchKeywords: ['nerve', 'brain', 'dimag', 'kamzori', 'tension', 'memory']
  },
  {
    id: 'ytm_29',
    name: 'Neuro Shakti Malt',
    hindiName: 'न्यूरो शक्ति माल्ट',
    category: Category.MEDICINE,
    benefits: 'Reduces numbness, relieves sciatica and back pain.',
    hindiBenefits: 'सुन्नपन कम करता है, साइटिका और कमर दर्द में राहत।',
    dosage: '1 spoon 30 mins after meals.',
    hindiDosage: 'खाने के 30 मिनट बाद 1 चम्मच।',
    description: 'Nerve health malt for pain management.',
    ingredients: ['Sunflower Seeds', 'Saunth'],
    searchKeywords: ['numbness', 'sunn', 'sciatica', 'back pain', 'nas', 'nerve', 'dard']
  },
  {
    id: 'ytm_30',
    name: 'Ojet Oil',
    hindiName: 'ओजेट ऑयल',
    category: Category.MEDICINE,
    benefits: 'Relieves back, neck, and joint pain.',
    hindiBenefits: 'कमर, गर्दन और जोड़ों के दर्द से राहत।',
    dosage: 'Massage gently onto affected area twice daily.',
    hindiDosage: 'प्रभावित क्षेत्र पर दिन में दो बार धीरे से मालिश करें।',
    description: 'Pain relief massage oil blend.',
    ingredients: ['Kali Musli', 'Menthol'],
    searchKeywords: ['oil', 'tel', 'pain relief', 'dard', 'massage', 'joint pain', 'kamar dard']
  },
  {
    id: 'ytm_31',
    name: 'NIXNIP DROP',
    hindiName: 'निक्सनिप ड्रॉप',
    category: Category.MEDICINE,
    benefits: 'Helps quit alcohol, smoking, and tobacco. Detoxifies.',
    hindiBenefits: 'शराब, धूम्रपान और तंबाकू छोड़ने में सहायक। डिटॉक्स।',
    dosage: '20-30 drops in water/meal twice daily.',
    hindiDosage: 'पानी या भोजन में 20-30 बूंदें दिन में दो बार।',
    description: 'Tasteless herbal addiction recovery drop.',
    ingredients: ['De-addiction herbs'],
    searchKeywords: ['addiction', 'nasha', 'sharab', 'alcohol', 'smoking', 'tambaku', 'quit']
  },
  {
    id: 'ytm_32',
    name: 'Panch Tulsi',
    hindiName: 'पंच तुलसी',
    category: Category.SUPPLEMENT,
    benefits: 'Boosts immunity, relieves cold, controls sugar.',
    hindiBenefits: 'इम्युनिटी बढ़ाता है, सर्दी से राहत और शुगर नियंत्रण।',
    dosage: '2-3 drops in water or tea 3-4 times a day.',
    hindiDosage: 'पानी या चाय में 2-3 बूंदें दिन में 3-4 बार।',
    description: 'Concentrated blend of 5 Tulsi types.',
    ingredients: ['Krishna', 'Ram', 'Shukla', 'Van', 'Nimbu Tulsi'],
    searchKeywords: ['tulsi', 'immunity', 'cold', 'sardi', 'khansi', 'cough', 'sugar']
  },
  {
    id: 'ytm_33',
    name: 'Onion Shampoo',
    hindiName: 'अनियन शैम्पू',
    category: Category.SKINCARE,
    benefits: 'Reduces hair fall, nourishes hair, and controls dandruff.',
    hindiBenefits: 'बालों का झड़ना कम करता है, पोषण देता है और डैंड्रफ नियंत्रित करता।',
    dosage: 'Use 3 times a week on wet hair.',
    hindiDosage: 'गीले बालों पर सप्ताह में 3 बार प्रयोग करें।',
    description: 'Natural onion-based shampoo for hair growth.',
    ingredients: ['Gudhal', 'Curry Leaves', 'Amla', 'Onion'],
    searchKeywords: ['shampoo', 'hair fall', 'baal', 'dandruff', 'growth', 'onion']
  },
  {
    id: 'ytm_34',
    name: 'Ambroliv Tablets & Tonic',
    hindiName: 'एम्ब्रोलिव टेबलेट्स और टॉनिक',
    category: Category.MEDICINE,
    benefits: 'Liver detox, improves appetite, protects liver cells.',
    hindiBenefits: 'लिवर डिटॉक्स, भूख में सुधार और लिवर कोशिकाओं की सुरक्षा।',
    dosage: 'Tabs: 1-2 tabs 3x/day. Tonic: 1-2 tsp as advised.',
    hindiDosage: 'गोली: 1-2 गोली 3 बार। टॉनिक: 1-2 चम्मच निर्देशानुसार।',
    description: 'Powerful remedy for liver function recovery.',
    ingredients: ['Liver-protecting herbs'],
    searchKeywords: ['liver', 'jigar', 'bhukh', 'detox', 'appetite']
  },
  {
    id: 'ytm_35',
    name: 'Ambrocid Tablets',
    hindiName: 'एम्ब्रोसिड टेबलेट्स',
    category: Category.MEDICINE,
    benefits: 'Quick relief from gas, bloating, and burning chest.',
    hindiBenefits: 'गैस, पेट फूलना और सीने में जलन से तुरंत राहत।',
    dosage: '2 tablets 3 times a day for 2 weeks, then 2x/day.',
    hindiDosage: '2 गोली दिन में 3 बार 2 हफ्ते तक, फिर दिन में 2 बार।',
    description: 'Fast-acting digestive antacid.',
    ingredients: ['Antacid herbs'],
    searchKeywords: ['gas', 'acidity', 'jalan', 'bloating', 'pet dard', 'digestion']
  },
  {
    id: 'ytm_36',
    name: 'Calciambro',
    hindiName: 'कैल्शिएम्ब्रो',
    category: Category.SUPPLEMENT,
    benefits: 'Strengthens bones, faster fracture healing, fights anemia.',
    hindiBenefits: 'हड्डियों की मजबूती, फ्रैक्चर का तेजी से भरना और एनीमिया से लड़ना।',
    dosage: '2 tablets 3 times a day.',
    hindiDosage: '2 गोली दिन में 3 बार।',
    description: 'Calcium and iron supplement for growth.',
    ingredients: ['Abha Guggul', 'Praval Bhasma'],
    searchKeywords: ['calcium', 'bones', 'haddi', 'height', 'iron', 'weakness']
  },
  {
    id: 'ytm_37',
    name: 'Bone Health Tablets',
    hindiName: 'बोन हेल्थ टेबलेट्स',
    category: Category.SUPPLEMENT,
    benefits: 'Bone density support, height growth for kids.',
    hindiBenefits: 'हड्डियों का घनत्व बढ़ाना और बच्चों की लम्बाई में सहायक।',
    dosage: 'Adults: 1 tab morning/evening. Kids: 1 tab daily.',
    hindiDosage: 'वयस्क: सुबह/शाम 1 गोली। बच्चे: रोजाना 1 गोली।',
    description: 'Nutrient blend for skeletal strength.',
    ingredients: ['Vitamin D3', 'Glucosamine'],
    searchKeywords: ['bones', 'haddi', 'height', 'vitamin d3', 'joint']
  },
  {
    id: 'ytm_38',
    name: 'Eczigo Powder',
    hindiName: 'एक्ज़ीगो पाउडर',
    category: Category.MEDICINE,
    benefits: 'Treats eczema, itching, scabies, and ringworm.',
    hindiBenefits: 'एक्जिमा, खुजली और दाद का इलाज करता है।',
    dosage: 'Half to one spoon twice daily with water.',
    hindiDosage: 'आधा से एक चम्मच दिन में दो बार पानी के साथ।',
    description: 'Herbal powder for chronic skin infections.',
    ingredients: ['Blood-cleansing herbs'],
    searchKeywords: ['skin', 'eczema', 'khujli', 'itching', 'infection', 'daadh']
  },
  {
    id: 'ytm_39',
    name: 'Dermy Tablet',
    hindiName: 'डर्मी टेबलेट',
    category: Category.MEDICINE,
    benefits: 'Reduces pimples, rashes, boils, and cleans blood.',
    hindiBenefits: 'पिंपल्स, रैशेज, फोड़े कम करता है और खून साफ करता है।',
    dosage: '2 tablets 3 times a day.',
    hindiDosage: '2 गोली दिन में 3 बार।',
    description: 'Clear skin formula from within.',
    ingredients: ['Skin-healing herbs'],
    searchKeywords: ['skin', 'pimple', 'muhase', 'blood purifier', 'rash', 'glow']
  },
  {
    id: 'ytm_40',
    name: 'GARCINIA CAMBOGIA',
    hindiName: 'गार्सिनिया कम्बोजिया',
    category: Category.SUPPLEMENT,
    benefits: 'Weight management, improves metabolism, reduces stress.',
    hindiBenefits: 'वजन नियंत्रण, मेटाबॉलिज्म में सुधार और तनाव में कमी।',
    dosage: '1 tablet 30 minutes BEFORE a meal.',
    hindiDosage: 'खाने से 30 मिनट पहले 1 गोली।',
    description: 'Ayurvedic fat burning support.',
    ingredients: ['Garcinia Extract'],
    searchKeywords: ['weight loss', 'vajan kam', 'fat loss', 'metabolism', 'motapa']
  },
  {
    id: 'ytm_41',
    name: 'Fitslim Capsules',
    hindiName: 'फिटस्लिम कैप्सूल्स',
    category: Category.SUPPLEMENT,
    benefits: 'Obesity management, metabolic support.',
    hindiBenefits: 'मोटापा प्रबंधन और मेटाबॉलिक सहायता।',
    dosage: 'Take after meals twice a day.',
    hindiDosage: 'दिन में दो बार भोजन के बाद लें।',
    description: 'Weight loss supplement with no side effects.',
    ingredients: ['Metabolic-boosting herbs'],
    searchKeywords: ['slim', 'fat', 'vajan', 'motapa', 'weight management']
  },
  {
    id: 'ytm_42',
    name: 'Jeevan Amrit Ras',
    hindiName: 'जीवन अमृत रस',
    category: Category.SUPPLEMENT,
    benefits: 'Repairs body cells and boosts immunity.',
    hindiBenefits: 'कोशिकाओं की मरम्मत और इम्युनिटी बढ़ाता है।',
    dosage: '15–30 ml twice a day.',
    hindiDosage: '15-30 मिली दिन में दो बार।',
    description: 'Premium antioxidant juice.',
    ingredients: ['Noni', 'Garcinia', 'Ashwagandha'],
    searchKeywords: ['immunity', 'energy', 'antioxidant', 'cell repair', 'shakti']
  },
  {
    id: 'ytm_43',
    name: 'Immuty Plus',
    hindiName: 'इम्युटी प्लस',
    category: Category.SUPPLEMENT,
    benefits: 'Fights bacteria, boosts muscle strength.',
    hindiBenefits: 'बैक्टीरिया से लड़ता है और मांसपेशियों की ताकत बढ़ाता है।',
    dosage: '20 ml morning/evening with warm water.',
    hindiDosage: '20 मिली सुबह/शाम गुनगुने पानी के साथ।',
    description: 'Fruit and veg-based immunity protector.',
    ingredients: ['Natural vitamins'],
    searchKeywords: ['immunity', 'strength', 'bacteria', 'muscles', 'shakti']
  },
  {
    id: 'ytm_44',
    name: 'Hair Grow Tablet',
    hindiName: 'हेयर ग्रो टेबलेट',
    category: Category.SKINCARE,
    benefits: 'Reduces hair fall and boosts new growth.',
    hindiBenefits: 'बालों का झड़ना कम करता है और नए विकास को बढ़ावा देता है।',
    dosage: '2 tabs 3x/day for 2 weeks, then 2x/day.',
    hindiDosage: '2 गोली दिन में 3 बार 2 हफ्ते तक, फिर दिन में 2 बार।',
    description: 'Root nourishment for hair health.',
    ingredients: ['Brahmi', 'Bhringraj', 'Amla'],
    searchKeywords: ['hair grow', 'baal', 'hair fall', 'growth', 'shiny hair']
  },
  {
    id: 'ytm_45',
    name: 'LIVICID Syrup',
    hindiName: 'लीविसिड सिरप',
    category: Category.MEDICINE,
    benefits: 'Relief from stomach pain and chest burning.',
    hindiBenefits: 'पेट दर्द और सीने में जलन से राहत।',
    dosage: '2 tsp 3 times a day.',
    hindiDosage: '2 चम्मच दिन में 3 बार।',
    description: 'Digestive tonic for stomach comfort.',
    ingredients: ['Digestive enzymes'],
    searchKeywords: ['gas', 'acidity', 'digestion', 'pachan', 'pet dard', 'burning']
  },
  {
    id: 'ytm_46',
    name: 'ACV Gummies',
    hindiName: 'एसीवी गमीज़',
    category: Category.SUPPLEMENT,
    benefits: 'Metabolism boost, reduces appetite.',
    hindiBenefits: 'मेटाबॉलिज्म बढ़ावा और भूख में कमी।',
    dosage: '1-2 gummies daily.',
    hindiDosage: 'रोजाना 1-2 गमीज़।',
    description: 'Weight management apple cider vinegar gummies.',
    ingredients: ['Apple Cider Vinegar', 'Beetroot'],
    searchKeywords: ['weight loss', 'vajan', 'metabolism', 'appetite', 'gummy']
  }
];
